"use strict";
exports.__esModule = true;
var base_ships_1 = require("./base-ships");
var star_fighters_1 = require("./star-fighters");
var ship = new base_ships_1.Spacecraft("hyperdrive");
ship.jumpIntoHyperspace();
var falcon = new star_fighters_1.MillenniumFalcon();
falcon.jumpIntoHyperspace();
var goodForTheJob = function (ship) { return ship.cargoContainer > 2; };
console.log("Is falcon good for the job? " + (goodForTheJob(falcon) ? "yes" : "no"));
